### ISSUE TITLE
Parsing of robot libraries in .py files

### ISSUE THREAD

**Issue by antoine-gallix** [andriyko/sublime-robot-framework-assistant#104]
I have a project where some robot libraries are written in python, lets say `CustomRobotLib.py`, whose folder is added in front of the system path.
In my robot test files, I can then import those libraries like this:
```
Library CustomRobotLib
```
However the assistant is unable to understand those types of import, even if the right folder is included in the "robot_framework_workspace". The errors in the `scan_index.log` looks like:

In NginxLayer.robot is a file importinng such a python written robot library 
```
INFO:2016-04-29 11:55:35,975: Creating table for: /home/antoine/code/c1-cre-api/eggs/c1_robotframework-0.1.22-py2.7.egg/c1/robotframework/daemon/nginx-layer.robot
INFO:2016-04-29 11:55:35,979: Creating table for: NginxLayer
WARNING:2016-04-29 11:55:35,980: Error in: NginxLayer
```
One of these libraries is `EggLoaderLibrary.py` and the log says:

```
INFO:2016-04-29 11:55:36,059: Creating table for: EggLoaderLibrary
WARNING:2016-04-29 11:55:36,060: Error in: EggLoaderLibrary
```

**Comment by aaltat** [comment]
The parsing relies on Robot Framework libdoc, actually some internal functionality of libdoc. Can you generate keyword documentation using libdoc? If you can then there is a bug in the plugin. If can't, then the plugin can't either.

**Comment by aaltat** [comment]
As a workaround, if the libdoc works or you get the XML document created in other ways, you could use the robot_framework_library_in_xml setting. The keyword from XML document are available globally, like BuildIn and the keyword completion works.

**Comment by aaltat** [comment]
Did you get the problem sorted out or should I investigate the problem?

**Comment by antoine-gallix** [comment]
Ok, it turns out that the robot script used in my company first adds all of our custom robot libraries libraries in the system path before starting, and thats why the parser doesn't find them. Libdoc works fine on them separately. So the problem doesn't come from the plugin.
My dir hierarchy looks like:
base/
     test/
         here are the test files
    lib/
        here are egg folder with `RobotLib.py` like files, used by my tests

specifying
`"robot_framework_workspace": "base"`
doesn't work when `Library  RobotLib` is on the top of one of my test files

**Comment by aaltat** [comment]
So this seems like it is resolved and therefore closing the issue. If it is not, please send a update and I will open the issue.
