### ISSUE TITLE
Ctrl + '/' does not toggle comment

### ISSUE THREAD

**Issue by chaussen** [andriyko/sublime-robot-framework-assistant#110]
the shortcut to toggle comment used to add '#' before a line to comment it out or back. now it is not working.

the log_commands shows:
```
>>> sublime.log_commands(True)
command: toggle_comment {"block": false}
```

it seems that the toggle input was detected, but did not take effect.

the Comments.tmPreferences file in robot folder is the same as the one in the repo:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Comments</string>
    <key>scope</key>
    <string>source.robot</string>
    <key>settings</key>
    <dict>
        <key>shellVariables</key>
        <array>
            <dict>
                <key>name</key>
                <string>TM_COMMENT_START</string>
                <key>value</key>
                <string># </string>
            </dict>
            <dict>
                <key>name</key>
                <string>TM_COMMENT_DISABLE_INDENT</string>
                <key>value</key>
                <string>no</string>
            </dict>
        </array>
    </dict>
    <key>uuid</key>
    <string>94fe6ba0-068c-4f3a-9eb2-d87ae1bf78aa</string>
</dict>
</plist>
```

**Comment by aaltat** [comment]
I can not reproduce the problem, with these details. For me comment togle works when I see this in the console:
```
command: toggle_comment {"block": false}
```
To a quick try could you try the following: 
- Could you look on the `Packages\User` folder that there are not configuration files which could affect the plugin. 
- Also by default plugin only works with files that have `.robot` extension. If you have other file extension, then comment togle does not work. 

If the above does not work for you, could you tell which version of Sublime Text you are using, on which OS you are using it and which version of plugin you are using.

**Comment by aaltat** [comment]
Also it could be useful if you could write a small example to demonstrate your problem

**Comment by chaussen** [comment]
i am using sublime 3 with the latest robot plugin in windows 7. it worked fine previously when there was still a 'Robot Framework Asistant' in the menu bar. now it fails to toggle .robot any more, but still works for other file type.

my file extension is robot. inside my packages/user, there are Color Highlighter folder, Package Control.cache folder, Neon (SublimePythonIDE).tmTheme, Package Control.last-run, Package Control.merged-ca-bundle, Package Control.sublime-settings, Package Control.system-ca-bundle, Package Control.user-ca-bundle, Preferences.sublime-settings, Solarized (Light) (SublimePythonIDE).tmTheme. nothing seems to be config.

how could i write a small example? 

cheers,
john

**Comment by aaltat** [comment]
The comment toggle relies on Sublime Text 3 [default functionality](http://docs.sublimetext.info/en/latest/reference/comments.html). Only thing the there needs to be, is a file ending [.tmPreferences](https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/Comments.tmPreferences) to define the comment characters for different types of scopes.

It could be that some reason, after the upgrade, you are still getting wrong scope for your *.robot files. Or sublime has cached settings from 1.X.X and therefore the plugin is not fully functional for you.

**Comment by aaltat** [comment]
And one more thing to try, could try toggle comment from the menu: `Edit -> Comment -> Toggle Comment` and see does it help.

**Comment by aaltat** [comment]
After some testing I am able to reproduce a similar problem, but I am not sure if it's the same problem as you are having. Or can I do something about it. 

Picture tells more than words: 
![sublime-text3-comment-toggle](https://cloud.githubusercontent.com/assets/2665023/14996614/8909d14c-1183-11e6-99f3-c4bd2df7870d.png)

If picture is looked closely enough, one can see that focus is not in the `test_a.robot` file, but the focus actually is in the console command line. Now if I do, `Edit -> Comment -> Toggle Comment` the command is recorded in the console, but nothing actually happens in the `test_a.robot` file. There are few other scenarios where the file seems to have focus, although it does not actually have and therefore the `Toggle Comment` does not work. 

@chaussen could it be that you did experience a similar situation?

**Comment by chaussen** [comment]
toggle comment from menu doesn't work either and i didn't see the focus issue you demonstrated. i can confirm the cursor is blinking in the file when i hit the button. 

actually i have more issues with the updated plugin. Alt + Enter going to a custom keyword in another file freezes the entire sublime while it works for keywords from robot libraries (database is created). auto-complete doesn't work at all for any keywords. no snippets show for any settings. it's not as convenient as before. i guess i have to reinstall the program and see what happen.

thanks.

**Comment by aaltat** [comment]
Sounds really strange and I haven't encounter such issues before. I hope that reinstall helps

**Comment by chaussen** [comment]
ok i have figured out what's wrong with comment. the new Robot.tmLanguage has slightly different way to define comment color. it doesn't have comment.robot and but has a comment character. i want to still use my old tmLanguage file because i have customised it. overwriting the new tmLanguage breaks the comment toggle.

**Comment by aaltat** [comment]
You are correct, the scope has changed from `commwnt.robot` to `comment`. If you want an easy way, you can get the old [tmLanguage](https://github.com/andriyko/sublime-robot-framework-assistant/blob/st2-maintenance/robot.tmLanguage) and overwrite the new one with old one. 

I didn't have any good reason to change the scope of the comment. If you want we can change it back in the 4.0.0 release, which should come out next in the near future.

**Comment by chaussen** [comment]
that's alright. i have already reinstalled sublime and made changes to the new robot tmLanguage file which works fine now. thanks
