### ISSUE TITLE
Sometimes it could useful to jump back to the keyword

### ISSUE THREAD

**Issue by aaltat** [andriyko/sublime-robot-framework-assistant#137]
When I jump to keyword, to read what the keyword actually does, it could be nice to be able to jump back to place where I did perform the keyword.

Example I am in `test_a.robot` which uses `Resource A Keyword 2` from `resource_a.robot`. When I am in `test_a.robot` and cursor is on the `Resource A Keyword 2` keyword, I jump to the `Resource A Keyword 2` in `resource_a.robot`. Then it would be hande, if I could jump to the `test_a.robot` where I did perform the jump.

**Comment by georgecarstoiu** [comment]
Isn't this done through Ctrl+Tab? From what I got from your scenario, this should work perfectly :)

**Comment by aaltat** [comment]
Not in all cases. Keyword may be in same file. Or keyword may be in file which is already open and `Ctrl+Tab` don't take user to right place.

**Comment by aaltat** [comment]
I do not have any need for this. Closing
