### ISSUE TITLE
Default configuration file gets overwritten on update

### ISSUE THREAD

**Issue by georgecarstoiu** [andriyko/sublime-robot-framework-assistant#138]
The plugin got updated automatically this morning to v4, but the default config file was overwritten. Was this done because of the two extra options were added to it?

**Comment by aaltat** [comment]
That is up to the package manager, which I do not control, but I ques default settings can be overwritten in all updates. 

One should not newer change default settings, instead user should define user specific settings. More details in the Sublime Text 3 [Unofficial documentation](http://docs.sublimetext.info/en/latest/customization/settings.html)

**Comment by georgecarstoiu** [comment]
Ok. Thanks for clarifying this for me :)
