### ISSUE TITLE
Syntax Highlighting Not Working For Text Files

### ISSUE THREAD

**Issue by snyderr** [andriyko/sublime-robot-framework-assistant#140]
I have ver 4.0.0 of Robot Framework Assistant installed an I am running it with Sublime Text Build 3114. Syntax highlighting with file types of `.robot` are working as expected but when a `.txt` file is opened Robot Framework Assistant does not recognize the file (no syntax highlighting). I have added text to the fileTypes key in the `Robot.tmLanguage` file but it is still not recognizing text files.

There are no errors being thrown in the console when attempting to use Robot Framework Assistant with a text file.

**Comment by aaltat** [comment]
This could sublime caching issue. But as a workaround, you should get it working by defining a user setting. Copy the `Robot.tmLanguage` to `Packages\User` folder and change the
```
<dict>
	<key>fileTypes</key>
	<array>
		<string>robot</string>
	</array>
```
to
```
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
```

I will try to figure out, where the problem actually is and write better instructions to the [README.md](https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/README.md)
