### ISSUE TITLE
Question about settings importer

### ISSUE THREAD

**Issue by huuhtaneno** [andriyko/sublime-robot-framework-assistant#161]
Hello,

Is it supposed to be possible to find custom libraries with the settings importer? As in a library located in the same folder as the test case?

Best regards,

Oliver

**Comment by aaltat** [comment]
You mean 
```
| *** Settings *** |
| Library | my_lib.MyLib | 
```
If I recall correctly Robot Framework will put the ${EXECDIR} or ${CURDIR} folder in the module search path automatically. But that feature is not supported by the plugin. You need to add manually add all the paths to the 
https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/README.md#robot_framework_module_search_path setting.

But this would be a useful feature to have. But if ${EXECDIR} is put in the module search path, then #152 should be fixed first. But if ${CURDIR} is put in module search path automatically, that should be relatively easy to fix.

Are you interested on making a pull request?

**Comment by huuhtaneno** [comment]
Okay, thanks for the quick reply. I could look into doing a pull request, but not sure if I have the time. 
I'll just use the module search path for now.

Thanks!
