### ISSUE TITLE
Project specific database not working

### ISSUE THREAD

**Issue by jrkoiter** [andriyko/sublime-robot-framework-assistant#171]
I've setup my Sublime project according to https://github.com/andriyko/sublime-robot-framework-assistant/wiki/How-To#project-specific-settings, but still the default database path is used. The provided setting for "robot_framework_database_path" is a valid directory. 

I'm on Mac 10.11.6, Sublime 3 build 3126 and RFA 5.1.1.

**Comment by aaltat** [comment]
Could you share the how you defined the project specific settings?

**Comment by jrkoiter** [comment]
Here is the content of the sublime-project file:

`{
	"folders":
	[
		{
			"path": "."
		}
	],
    "robot_framework_assistant":
    {
        "robot_framework_workspace": "/Users/joost/Documents//SystemTests",
        "robot_framework_database_path": "/Users/joost/Documents/SystemTests/SystemTests.database"
    }
}
`

**Comment by aaltat** [comment]
Thank you from the input. I will take a look later in the evening.

**Comment by aaltat** [comment]
I can produce the same problem with my environment and it is a bug. I need to find where it is broken, fix it and make a new release.

**Comment by aaltat** [comment]
This should be now fixed and new release should be soon available from Package Control. Please update if the problem has not been fixed.
