### ISSUE TITLE
Robot.sublime-build

### ISSUE THREAD

**Issue by huuhtaneno** [andriyko/sublime-robot-framework-assistant#172]
Hi,

I have noticed that every time the plugin updates, my Robot.sublime-build file is overwritten. Any chance this could be avoided?

**Comment by aaltat** [comment]
You should define the [user settings](http://docs.sublimetext.info/en/latest/customization/settings.html?#where-to-store-user-settings-once-again), they are not overwritten by the plugin update.  From Sublime menus: `Preferences -> Package Settings -> Robot Framework Assistant -> Settings - User`

**Comment by huuhtaneno** [comment]
Okay, I didn't know that the build settings can also be defined here. So I can just add this to my settings:

    "cmd": ["python", "-m", "robot.run", "-d", "C:\\tmp\\output", "-L", "TRACE", "$file"],
    "selector": "source.robot",
    "variants": [

        { "name": "Selects the test cases by tag",
          "cmd": ["python", "-m", "robot.run", "--include", "REPLACE_WITH_TAG", "$file"],
        },

        { "name": "Selects the test cases by name",
          "cmd": ["python", "-m", "robot.run", "--test", "REPLACE_WITH_TEST_NAME", "$file"]
        }
    ]

**Comment by aaltat** [comment]
That is a build setting? But in practice yes, one can also define also user specific build settings. Just remember to choose the right build settings when starting Robot test.

**Comment by huuhtaneno** [comment]
That was my initial question. Is there a way of not overwriting the build settings on update?

**Comment by aaltat** [comment]
Ah. I did miss read the question, sorry. But same rule applies, define a user build setting in the same folder where other user defined settings goes. The user defined settings are never overwritten by the plugin.

**Comment by huuhtaneno** [comment]
Okay, this worked thanks for your help!

**Comment by aaltat** [comment]
No problem and glad to help
