### ISSUE TITLE
shift+click to select text is broken when installed

### ISSUE THREAD

**Issue by kevin--** [andriyko/sublime-robot-framework-assistant#174]
If I install Robot Framework Assistant, then try to select text by holding SHIFT, and clicking, nothing happens!
Expected behavior is that the text from the current caret position is selected until the position that you clicked on.

Removing this package instantly fixes the issue.

OS X 10.11.6
Sublime Text Stable Channel 3126
Robot Framework Assistant v5.1.2
All file extensions are affected

**Comment by aaltat** [comment]
I haven't used that shortcut, could you explain what actually should happen? In what file extension this happens and if it's not a normal txt file, could you show an example?

Also what is the sublime text and plugin version that you are using?

**Comment by aaltat** [comment]
If you open sublime console do you see any errors or stack trace when you execute the shortcut? If you do could you copy/paste it to here?

If you don't see any errors could you execute `sublime.log_input(True)` in the console. And then execute the shortcut with plugin installed and when it's installed.

**Comment by endqwerty** [comment]
> I haven't used that shortcut, could you explain what actually should happen? In what file extension this happens and if it's not a normal txt file, could you show an example?
This is the common behavior across operating systems where if you shift+left-click then the text is selected from the original cursor location to the new cursor location.

I have the same issue with build 3126 and plugin version 5.1.2

It appears that shift+left-click is being used as a shortcut for either 'Jump to Keyword' or 'Show Keyword Documentation' as "... not found from db" error

**Comment by aaltat** [comment]
The Mac and other operating system mouse maps are different because Mac keyboard is different. In other mouse maps modifier key is `Alt`

To temporally overcome the problem you can define user mouse map set the modifier key as you want.

I am open to suggestions how to fix it in the next release. Which modifier key(s) you would like to use in Mac to show the documentation with mouse.

**Comment by kevin--** [comment]
most IDEs "find definition" with Ctrl+Click, or on Mac, Cmd+Click

**Comment by aaltat** [comment]
`Ctrl` sounds fine by me. But I don't have Mac where I could test the fix. @kevin-- could you copy the https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/Default%20(OSX).sublime-mousemap file to the `Packages/User` folder. Then change line ```      "button": "button1", "count": 1, "modifiers": ["shift"],``` to ```      "button": "button1", "count": 1, "modifiers": ["ctrl"],```. Restart of sublime maybe required.

If that works I could make a new release to fix it officially.

**Comment by aaltat** [comment]
Or even pull request to provide the fix could be nice too.

**Comment by kevin--** [comment]
yes, changing the modifier to `ctrl` works great

**Comment by aaltat** [comment]
Fixed in https://github.com/andriyko/sublime-robot-framework-assistant/commit/8c36fdd4e77ce2dda03ff9e349237f3a8b699408

**Comment by aaltat** [comment]
There are few [minor things](https://github.com/andriyko/sublime-robot-framework-assistant/milestone/15) to be fixed before next release. Once those are done, I will create a new release.
