### ISSUE TITLE
The snippet for Test Cases is wrong

### ISSUE THREAD

**Issue by yanxurui** [andriyko/sublime-robot-framework-assistant#181]
The original code in Context.sublime-menu is like this:

    ...
    {
        "caption": "*** Test Cases ***",
        "command": "insert_snippet",
        "args": {
            "name": "Packages/Robot Framework Assistant/snippets/rfde-keywords-table-keywords.sublime-snippet"
        }
    },
    ...

So keywords should be replaced with testcases

The pull request is in #180

**Comment by yanxurui** [comment]
#180

**Comment by aaltat** [comment]
Done in #180
