### ISSUE TITLE
Intellisense is working only for resources available in the same .robot file?

### ISSUE THREAD

**Issue by accesslubos** [andriyko/sublime-robot-framework-assistant#199]
~~When I'm scripting my keywords I usually define a keyword in *** Keywords *** part and call it from *** Test Cases ***~~
~~However intellisense works globally only in *** Test Cases *** - when I try to use it from *** Keywords *** I get only local keyword names. Is there something I missed during the setup?~~
Editing as it's probably caused by different thing. Do I have to have the resources as a part of each file in order to make intellisense working even if I don't have to from RF perspective? In my codebase there's quite a lot of pure keyword files where are only keywords available. They are all linked together in one commonsetup.robot file, so I guess that is why.

Thanks for your help in advance!

**Comment by aaltat** [comment]
I don't understand what intellisense is in your question, could you please clarify your problem?

**Comment by aaltat** [comment]
Closing due inactivity
