### ISSUE TITLE
"Jump To Keyword" not working with Prefix Given/When/Then

### ISSUE THREAD

**Issue by Noordsestern** [andriyko/sublime-robot-framework-assistant#209]
When describing testcases in BDD, Keywords start with a prefix _given_, _when_ or _then_ (ignore case).

Problem is: Jump To Keyword does not work in testcases written in Gherkin syntax.

Example of an executible test:
```robot
*** Testcases ***
My test story
    Given foo
    when bar
    tHen isSuccess

*** Keywords ***
foo
    print 'foo'

bar
    print 'bar'

isSuccess
    print 'ok'
```

Using `Jump To Keyword` on `foo` leads to `Keyword not found in db`.

It would be very helpful, if keywords could be found from within test stories, too.

**Comment by aaltat** [comment]
Did I get it right, that if you remove the prefix Given/When/Then then the `Jump To Keyword` works in your environment? If yes, I think you are right and the prefix is not removed when keyword is searching is done. 

I think removing the prefix is a could be good feature to have, would you like to provide a PR to implement the feature?

**Comment by aaltat** [comment]
Done in #210
