### ISSUE TITLE
The package path in the Context.sublime-menu file is inconsistent with the actual path

### ISSUE THREAD

**Issue by fy975713384** [andriyko/sublime-robot-framework-assistant#227]
The path to the package in the Context.sublime-menu file is `...Packages/Robot Framework Assistant/...`, 
but the directory that is actually created automatically on my computer is `...Packages/RobotFrameworkAssistant/...` .
I want to understand what caused this difference. This difference cause certain features in the context to not work properly.

**Comment by idxn** [comment]
Face the same problem

**Comment by chaussen** [comment]
i removed all spaces between robot and framework and assistant inside the context file and it works. but it should be fixed.
