### ISSUE TITLE
importing external Libs failure/oddities

### ISSUE THREAD

**Issue by yahman72** [andriyko/sublime-robot-framework-assistant#33]
Don't know if this a feature or bug.

Autocomplete works only if the externaly library is imported in file you are working with.
E.g.
`MyTests.robot` imports `SSHLibrary` & `MyResource.robot` & uses keywords from `SSHLibrary`
`MyResource.robot` imports nothing & uses keywords from `SSHLibrary`

RF executes the tests without errors, because for the RF it's enough to import `SSHLibrary` once.
Now editing MyResource.robot when trying to autocomplete something from SSHLibrary does not work, but it works only if the SSHLibrary is explicitly imported i.e.
`MyTests.robot` imports `SSHLibrary` & `MyResource.robot` & uses keywords from `SSHLibrary`
`MyResource.robot` imports `SSHLibrary` & uses keywords from `SSHLibrary`

If this is a feature, then it would be worth mentioning it in the README.

**Comment by andriyko** [comment]
```
Autocomplete works only if the externaly library is imported in file you are working with.
```
The description of issue is not clear. Please provide simplified examples of your files. Do you have data from rfdocs.org? Also what is your scanners configuration? Did you try to "Scan > All"?

**Comment by yahman72** [comment]
Below more details, but before that:
Why is the data from rfdocs.org relevant? Does the scan read the data from the data from the docs (i.e. downloaded from rfdocs.org) or from the sources (i.e. libs/site-packages)?

MyTests.robot
<pre>
*** Settings ***
Library     SSHLibrary
Resource    MyResource.robot

*** Test Cases ***
foo
    Put \ctrl+space here shows the options Put File / Put Directory\
</pre>

MyResource.robot
<pre>
*** Settings ***
Library     Collections

*** Keywords ***
MyKw
    Put \ctrl+space here shows nothing\
</pre>

Scanners config:
<pre>
            {
                "parser": "user_scanners.external.PythonLibsScannerExternal",
                "libraries": ["SSHLibrary", "AppiumLibrary"],
                "is_active": true,
                "package": ""
            }
</pre>

and yes, I tried "scan-all" but it didn't help, also tried restarting sublime + scan all.

I got working only after I included the SSHLibrary in the MyResources.robot (+ "scan all") i.e. when it looks like this it works:
<pre>
*** Settings ***
Library     Collections
Library     SSHLibrary

*** Keywords ***
MyKw
    Put \ctrl+space here shows the options Put File / Put Directory\
</pre>

Just in case this is relevant:
After running "scan all" the console shows this 
<pre>
rfassistant.commands.scan_local_data_command: 
rfassistant.commands.scan_local_data_command: 
</pre>
i.e. it's a bit hard to say what happens since nothing is printed

**Comment by andriyko** [comment]
@yahman72 , please see [READEME](https://github.com/andriyko/sublime-robot-framework-assistant#edit-scanners). Scanners read data from rfdocs.org (if not disabled) and from you local librs/resources defined in scanners configuration.

**Comment by yahman72** [comment]
I have read it, but still unclear how this should work.
I don't want to use rfdocs, because the external libs are out-dated there (e.g. appiumLibrary) and I want to get it also working with my own libraries.

btw. the README doesn't say how to disable rfdocs.

**Comment by andriyko** [comment]
To disable rfdocs.org: `Robot Framework > Show data directories`, then delete `rfdocs` folder.
```
I want to get it also working with my own libraries.
```
Read [this](https://github.com/andriyko/sublime-robot-framework-assistant#edit-settings) and [this](https://github.com/andriyko/sublime-robot-framework-assistant#edit-scanners)
