### ISSUE TITLE
Robot Framework 2.9 support

### ISSUE THREAD

**Issue by aaltat** [andriyko/sublime-robot-framework-assistant#37]
More an discussion and not an issues, but in anyway...

Because the 2.9 moved to beta phase and it has quite big changes, like: https://github.com/robotframework/robotframework/issues/1952, https://github.com/robotframework/robotframework/issues/1818, https://github.com/robotframework/robotframework/issues/1450, https://github.com/robotframework/robotframework/issues/925 and so on. @andriyko have you given any though how this should be done? If you have, have you done any work for it? If you have, can I help?

**Comment by andriyko** [comment]
@aaltat could you please provide uses-cases and examples on how to use new syntax?

**Comment by aaltat** [comment]
@andriyko are you still supporting (and using) the plugin? I have been building [new plugin](https://github.com/aaltat/robotframework-from-sublime), based on the idea that keywords would be found based on the imports in RF data. To work is not complete, but the first beta release is quite near.

Instead building a yet another plugin in sublime package control (and yet another RF IDE in Robot Framework community) and if you are anymore maintaining this plugin, I was wondering would it possible to transfer the plugin ownership to me and I would continue developing it?

**Comment by aaltat** [comment]
I guess those mails means that you said yes. @andriyko, how you want to do this? Do you want still participate, in some way, or am I free do as I want?

**Comment by andriyko** [comment]
@aaltat You are free to do as you want. My participation can be as a "help" if you need it.
However, I don't want to transfer it to another account. As a collaborator you have all the [permissions](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account) needed to do what you want.

**Comment by aaltat** [comment]
Understood, let's go like that.

**Comment by andriyko** [comment]
:+1:

**Comment by aaltat** [comment]
Closing because of the rewrite.
