### ISSUE TITLE
Migrate rfdocs manifests and packages to github.

### ISSUE THREAD

**Issue by Chaser** [andriyko/sublime-robot-framework-assistant#38]
The plugin is great but with rfdocs.org not currently available it would be ideal to add these manifests and packages somewhere else.

**Comment by andriyko** [comment]
You can run rfdocs locally https://github.com/andriyko/rfdocs and configure the plugin to get data from localhost. I can bring rfdocs.org up, but i do not want to pay my own money for the hosting as it was during 2 years. So, if Robot Framework users really need rfdocs.org, i suggest to discuss it in google group.
