### ISSUE TITLE
Current file user keywords "goto" is not working 

### ISSUE THREAD

**Issue by radinsky** [andriyko/sublime-robot-framework-assistant#41]
Current file user keywords "goto" is not working, testcase scanner is enabled:
 "testcase_scanner":
        {
            "parser": "scanners.standard.TestCaseFilesScannerStandard",
            "is_active": true
        }

what can be wrong?

**Comment by andriyko** [comment]
Please give more details. Paste snippets of your resource and test files.

**Comment by radinsky** [comment]
Attaching my code.
```
*** Settings ***
Documentation     See [http://www.robotframework.org|robot framework website]
Library           String

*** Test Cases ***
case
    keyword
    keyword2
    keyword3
    keyword4
    keyword5
    keyword6
    Comment    ${message}=    Evaluate    "%-17s %5s\\n%-17s %5s" % ('received:', '1111','sent:', '5')

*** Keywords ***
keyword
    Return From Keyword    11    42

keyword2
    ${first} =    Catenate    SEPARATOR=,    a
    ${first} =    Catenate    SEPARATOR=,    ${first}    b
    ${first} =    Catenate    SEPARATOR=\n    ${first}    c
    ${first} =    Catenate    SEPARATOR=,    ${first}    d
    ${first} =    Catenate    SEPARATOR=,    ${first}    b
    ${first} =    Catenate    SEPARATOR=\n    ${first}    c
    ${first} =    Catenate    SEPARATOR=,    ${first}    d
    Log To Console    ${first}

keyword3
    Set Global Variable    ${e}    http://google.com
    Set Test Message    *HTML*<a href="${e}">asd</a>

keyword4
    ${a}    ${b}    keyword

keyword5
    ${sum}=    Set Variable    [SUM] \ 0.0-10.0 sec \ \ \ 493 MBytes \ 49.2 MBytes/sec
    Comment    ${sum}    ${cut}=    Split String From Right    ${sum}    ${SPACE}
    Comment    ${cut}    ${rate}=    Split String From Right    ${sum}    ${SPACE}
    ${rate}=    Fetch From Right    ${sum}    Bytes \ \
    ${rate}=    Fetch From Left    ${rate.strip()}    ${SPACE}
    BuiltIn.Log    ${rate}

keyword6
    Set Suite Documentation    *HTML*<a>test</a>

```

When press ALT Click I getting:
![image](https://cloud.githubusercontent.com/assets/4540268/13315395/288ee5ba-dbb3-11e5-81ae-c5b035df37dc.png)

If I press ALT Click on Set Suite Documentation, it takes me to the right place:
![image](https://cloud.githubusercontent.com/assets/4540268/13315428/456c0082-dbb3-11e5-83d1-85e402b9df20.png)

**Comment by aaltat** [comment]
If I recall correctly, scanning keywords from test suites is not supported by the plugin. Would have to read the code to be sure.

To confirm the assumption, if you put the keywords to a resource file and configure the scanner accordingly does it then work?

**Comment by radinsky** [comment]
No, not worked for me as well also when i put it as resource file.

**Comment by aaltat** [comment]
Did you remember to configure scanner, scan and index? The plugin creates a database to the plugin installation directory. In robot_data directory you should find a file which has a same name as your resource file. If the file is not there the scanner is not configured correctly but if the file is there, problem is somewhere else.

Sorry that cannot give more detailed instructions, where to look, but I am not with my PC. If you cannot locate the right folders, just let me know and I will give better instructions later.

**Comment by aaltat** [comment]
@radinsky Did you get this one solved and can we close the issue?

**Comment by aaltat** [comment]
Because did not hear any assuming that issue if fixed and closing the issue. If this still is a issue, please open the issue.

**Comment by radinsky** [comment]
The issue is still exist.
@aaltat The file is created in robot_data directory with all keywords from my resource file.

**Comment by aaltat** [comment]
Reopened the issue. Could you share the whole scanner file?

**Comment by radinsky** [comment]
`{
    "paths":
        [
        ],

    "pylib_scanners": [
            {
                "parser": "scanners.standard.PythonLibsScannerStandard",
                "libraries": ["BuiltIn", "OperatingSystem", "Collections",
                              "Telnet", "XML", "Dialogs",
                              "String", "Process", "Screenshot", "Remote"],
                "is_active": true,
                "package": "robot.libraries"
            },
            {
                "parser": "user_scanners.external.PythonLibsScannerExternal",
                "libraries": ["SeleniumLibrary", "SSHLibrary", "Selenium2Library"],
                "is_active": false,
                "package": ""
            }
        ],
    "resource_scanners": [
        {
            "parser": "scanners.standard.ResourceFilesScannerStandard",
            "path": "%userprofile%/Desktop/test.robot",
            "is_active": true
        }
    ],
    "testcase_scanner":
        {
            "parser": "scanners.standard.TestCaseFilesScannerStandard",
            "is_active": true
        }
}
`

**Comment by radinsky** [comment]
AppData\Roaming\Sublime Text 3\Packages\Robot Framework Assistant\robot_data\current\current_data.json
`{
    "C:\\Users\\ralex\\Desktop\\test.robot": {
        "keywords": [
            {
                "documentation": "", 
                "name": "keyword", 
                "arguments": ""
            }, 
            {
                "documentation": "", 
                "name": "keyword2", 
                "arguments": ""
            }, 
            {
                "documentation": "", 
                "name": "keyword3", 
                "arguments": ""
            }, 
            {
                "documentation": "", 
                "name": "keyword4", 
                "arguments": ""
            }, 
            {
                "documentation": "", 
                "name": "keyword5", 
                "arguments": ""
            }, 
            {
                "documentation": "", 
                "name": "keyword6", 
                "arguments": ""
            }
        ], 
        "path": "C:\\Users\\ralex\\Desktop\\test.robot", 
        "variables": [], 
        "resource": "Test"
    }
}`

**Comment by aaltat** [comment]
Which version of Sublime you are using? If you are using Sublime Text 3, could you tell the build number too?

**Comment by aaltat** [comment]
Now I remember. It is not possible to parse keywords from test suite file and your `test.robot` is a test suite file because it contains ```*** Test Cases ***````  table. If you open the console from Sublime, you should see something like this: ```rfassistant.commands.scan_local_data_command: Failed to parse file: C:\Users\UserName\Desktop\test.robot. Error was: Resource file 'C:\Users\UserName\Desktop\test.robot' contains a test case table which is not allowed.```


If you move the ```*** Keywords ***``` table to `resource.robot` file, example like this:
```
*** Keywords ***
keyword
    Return From Keyword    11    42

keyword2
    ${first} =    Catenate    SEPARATOR=,    a
    ${first} =    Catenate    SEPARATOR=,    ${first}    b
    ${first} =    Catenate    SEPARATOR=\n    ${first}    c
    ${first} =    Catenate    SEPARATOR=,    ${first}    d
    ${first} =    Catenate    SEPARATOR=,    ${first}    b
    ${first} =    Catenate    SEPARATOR=\n    ${first}    c
    ${first} =    Catenate    SEPARATOR=,    ${first}    d
    Log To Console    ${first}

keyword3
    Set Global Variable    ${e}    http://google.com
    Set Test Message    *HTML*<a href="${e}">asd</a>

keyword4
    ${a}    ${b}    keyword

keyword5
    ${sum}=    Set Variable    [SUM] \ 0.0-10.0 sec \ \ \ 493 MBytes \ 49.2 MBytes/sec
    Comment    ${sum}    ${cut}=    Split String From Right    ${sum}    ${SPACE}
    Comment    ${cut}    ${rate}=    Split String From Right    ${sum}    ${SPACE}
    ${rate}=    Fetch From Right    ${sum}    Bytes \ \
    ${rate}=    Fetch From Left    ${rate.strip()}    ${SPACE}
    BuiltIn.Log    ${rate}

keyword6
    Set Suite Documentation    *HTML*<a>test</a>
```

And configure the `Robot Framework Assistant.scanners` to like this:
```
{
    "paths":
        [
        ],

    "pylib_scanners": [
            {
                "parser": "scanners.standard.PythonLibsScannerStandard",
                "libraries": ["BuiltIn", "OperatingSystem", "Collections",
                              "Telnet", "XML", "Dialogs",
                              "String", "Process", "Screenshot", "Remote"],
                "is_active": true,
                "package": "robot.libraries"
            },
            {
                "parser": "user_scanners.external.PythonLibsScannerExternal",
                "libraries": ["Selenium2Library"],
                "is_active": false,
                "package": ""
            }
        ],
    "resource_scanners": [
        {
            "parser": "scanners.standard.ResourceFilesScannerStandard",
            "path": "C:\\Users\\UserName\\Desktop",
            "is_active": true
        }
    ],
    "testcase_scanner":
        {
            "parser": "scanners.standard.TestCaseFilesScannerStandard",
            "is_active": true
        }
}
```
And run the commands: ```Robot Framework Assistant: Scan Python Libraries and Text Resources``` and ```Robot Framework Assistant: Reindex packages```. Then the jump to keyword should work.

**Comment by radinsky** [comment]
I'm with Sublime 3 build 3103
![image](https://cloud.githubusercontent.com/assets/4540268/14670794/431ee06e-06f7-11e6-8dff-cfe32b69cbde.png)

I checked the sublime console and I don't see the error you mentioned: 
> Error was: Resource file 'C:\Users\UserName\Desktop\test.robot' contains a test case table which is not allowed.

But when I do Scan All i got:
> Robot Framework Assistant.rfassistant.commands.scan_local_data_command: b''

Tried to create the resource.robot file as you described, it not helped me.

Also, regarding the commands you mentioned, I did them all from Robot Framework menu on the top:
![image](https://cloud.githubusercontent.com/assets/4540268/14670869/9d32a0b8-06f7-11e6-96cc-097821bb0e77.png)

**Comment by aaltat** [comment]
There is something wrong with the setup. In the `Robot Framework Assistant.scanners` file in `resource_scanners` `path` contains the path to the folder were the `test.robot` and `resource.robot` files are located?

And then you did run the *Robot Framework | Scan | All* command from the menu? In this case you must see the:
```
Error was: Resource file 'C:\Users\UserName\Desktop\test.robot' contains a test case table which is not allowed.
```
If you don't see it, then there's something wrong with the setup and therefore the jump to keyword does not work.

**Comment by aaltat** [comment]
Because the releases 3.0.0 and 3.0.1 are out and you are Sublime Text 3 user, is still valid bug for you? Because the release 3.0.0 removes the ```Robot Framework Assistant.scanners``` file and changes how keyword jump works.

**Comment by aaltat** [comment]
@radinsky is this still a problem for you or can we close the issue?

**Comment by radinsky** [comment]
@aaltat sorry for delay.

I didn't understand your resolution, should I downgrade my Sublime to 3.0.0, am I right?

**Comment by aaltat** [comment]
Sorry I was unclear. I mean that Robot Framework Assistant plugin version 3.0.0 did rewrite whole plugin. And because of the rewrite, the scanner configuration is not anymore needed. Therefore I was thinking that this problem is not anymore valid for you.

**Comment by radinsky** [comment]
My version is the most recent version from the git

**Comment by aaltat** [comment]
So does the jump to keyword work then work with the new version?

**Comment by radinsky** [comment]
Validate now with most recent version from git, now even the build in keywords stoped working and i getting in terminal:


>>> 
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 231, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 327, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "C:\Users\ralex\AppData\Roaming\Sublime Text 3\Packages\Robot Framework Assistant\commands\change_index.py", line 9, in on_activated
    message = update_current_view_index(view)
  File "C:\Users\ralex\AppData\Roaming\Sublime Text 3\Packages\Robot Framework Assistant\command_helper\update_current_view_json.py", line 11, in update_current_view_index
    workspace = get_setting(SettingObject.workspace)
  File "C:\Users\ralex\AppData\Roaming\Sublime Text 3\Packages\Robot Framework Assistant\setting\setting.py", line 137, in get_setting
    return get_sublime_setting(setting)
  File "C:\Users\ralex\AppData\Roaming\Sublime Text 3\Packages\Robot Framework Assistant\setting\setting.py", line 155, in get_sublime_setting
    project_setting = parse_project(setting)
  File "C:\Users\ralex\AppData\Roaming\Sublime Text 3\Packages\Robot Framework Assistant\setting\setting.py", line 144, in parse_project
    if SettingObject.project_setting in project_data:
TypeError: argument of type 'NoneType' is not iterable

**Comment by aaltat** [comment]
It seems that Sublime unofficial documentation is not correct on [projects](http://docs.sublimetext.info/en/latest/file_management/file_management.html?highlight=project#projects) and project doesn't always exist. Or there might be bug in Sublime. In any case, as a workaround you can create project and the problem should go away.

After project is created is created, do you still have the  original problem?

**Comment by aaltat** [comment]
I did raise #128 about the above project problem

**Comment by aaltat** [comment]
The #128 is now fixed in the master

**Comment by aaltat** [comment]
Is this still a problem or can we close it?

**Comment by radinsky** [comment]
I got the most recent version of Sublime and the plugin version from master.
Not it's not working at all. Even the build in keywords, i'm always getting 
![image](https://cloud.githubusercontent.com/assets/4540268/15453420/fa5071d2-201d-11e6-8715-cd87e9dff718.png)

Not sure if that's the same or related issue, if not, you can close this bug.

**Comment by aaltat** [comment]
The message means that the current file is not found from the internal database. Which indicates that the plugin is not correctly configured or/and internal database is not created. Could you check the configuration based on the [README](https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/README.md). Please remember to remove all the 1.x.x version configurations, because they are not anymore compatible with the version 4.0.0. After checking the configuration, create the internal database, more details in the [wiki](https://github.com/andriyko/sublime-robot-framework-assistant/wiki/Internal-database-for-keywords-and-variables).

After the internal database creation, check out the log file under the plugin installation directory, it is in the `database/scan_index.log` file.

**Comment by aaltat** [comment]
If there is a problem after the checks and the log file does not reveal any specific errors, could you send me the user specific [Robot.sublime-settings](https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/Robot.sublime-settings) file. Also enable [log_commands](https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/README.md#robot_framework_log_commands). Then perform again the internal database creation and send the output from the Sublime console. Also sending the `database/scan_index.log` could be useful.

**Comment by aaltat** [comment]
The underlying problem is the same, jump to keyword does not work. The problem does not go away if we close this pr and open a new one. So lets keep this open and try to figure out the problem.

Did you have any luck to hunt down the problem?

**Comment by radinsky** [comment]
Attaching my  Robot.sublime-settings

`
/*
    Robot Framework Assistant default settings
*/
{
    /*
        Sublime settings to make Robot Framework data editing more
        clearer and easier. Refer the Sublime default settings for
        more details.
    */
    "translate_tabs_to_spaces": true,

    "trim_trailing_white_space_on_save": true,

    "draw_white_space": "all",

    /*
        Same as the Sublime default in Build 3103 with one exception,
        it does not contain the * character. When the * is not in
        word_separators the snippets containing * in tabTrigger
        work out of the box.

        If * is needed as a word separator, then the snippets
        should be accessed by pressing tab key multiple times.

    */
    "word_separators": "./\\()\"'-:,.;<>~!@#$%^&|+=[]{}`~?",

    /*
        Robot Framework Workspace

        Defines a root folder where Robot Framework Assistant starts looking
        for Robot Framework data. Before the Robot Framework Assistant
        can provide the keyword and variable completion features, it needs
        to scan and index the test suite and resource files. The argument
        defines the root folder where scanning of robot data is performed.

        In windows the backslash is the folder separator and in json
        backslash is the escape character. Therefore, in windows write
        double backslash to write literal backslash.

    */
    "robot_framework_workspace": "C:\\python27_x64\\Lib\\site-packages\\robot",

    /*
        Defines how keyword argument are formatted when keyword
        completion is used. When set to false, each argument is
        formatted to individual lines. If set to true keyword
        and arguments are returned in single line.
    */
    "robot_framework_keyword_argument_format": false,

    /*
        File extension defines which types of files the Robot Framework
        Assistant plugin will search and index from the folder defined
        in the robot_framework_workspace option.

        This setting does not affect to the which files are uses the
        syntax highlight.
    */

    "robot_framework_extension": "robot",

    /*
        Path to Python binary

        In order the scanning and indexing of keywords and variables to
        work, path to Python binary must be defined. It must be the same
        Python binary where the Robot Framework is installed.

        In Linux like environments this could be like: /usr/bin/python
        and in Windows this could be like: C:\Python27\python.exe
    */

    "path_to_python": "C:\\python27_x64\\python.exe",

    /*
        Module search path defines a list of paths where the
        Robot Framework libraries are searched. Example if you have imported
        a library with the library name, then module search path must
        contain the folder where the library can be located.

        The Robot Framework Assistant uses the Robot Framework API to parse
        the test data and libraries. All changes, which are not system
        wide, to locate the libraries, must also be added in the
        module search path in the Robot Framework Assistant

        More details how libraries is searched in Robot Framework can be
        found from be the Robot Framework User guide:
        http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#module-search-path

    */
    "robot_framework_module_search_path":
        [
            "C:\\python27_x64\\Lib\\site-packages\\robot\\libraries"
        ],

    /*
        Database table creation

        The robot_framework_automatic_database_table setting controls the
        internal database updating. If the set to true, the internal
        database tables are created after a Robot Framework test data
        file is saved. If set to false, the internal database tables are
        only updated when the `Create Database`, `Create Database Tables`
        or `Create Database Table From Active Tab`
        commands are run.

        The setting only controls the Robot Framework test data. If a
        libraries or a variable files are updated, then `Create Database`,
        `Create Database Tables` or `Create Database Table From Active Tab`
        commands must be run to update the internal database.

    */
    "robot_framework_automatic_database_table": true,

    /*
        Automatic indexing for test data

        The robot_framework_automatic_indexing setting controls is
        a test data file automatically indexed. The automatic indexing
        can happen after these events:
        1) After a file is saved
        2) Jump To Keyword command is done
        3) Robot Framework file is changed

    */
    "robot_framework_automatic_indexing": true,

    /*
        Robot Framework libraries in XML

        When the library is not available during parsing time,
        example if library is imported with Remote library interface.
        Then this setting can be used to import libraries in libdoc XML
        format.

        Libraries found from the this path are globally available, in
        same manner as the BuiltIn library

    */
    "robot_framework_libraries_in_xml": "/path/to/library/documentation",

    /*
        Robot Framework variables

        Robot Framework comes by default some predefined and built in
        variables. These variables names may change between different
        Robot Framework versions. Use this setting to define the
        Robot Framework default variables.

        The variables in the default settings are from Robot Framework
        version 2.9.2

    */
    "robot_framework_builtin_variables":
        [
            "${/}",
            "${:}",
            "${\\n}",
            "${CURDIR}",
            "${DEBUG_FILE}",
            "${EMPTY}",
            "@{EMPTY}",
            "&{EMPTY}",
            "${EXECDIR}",
            "${False}",
            "${LOG_FILE}",
            "${LOG_LEVEL}",
            "${None}",
            "${null}",
            "${OUTPUT_DIR}",
            "${OUTPUT_FILE}",
            "${PREV_TEST_MESSAGE}",
            "${PREV_TEST_NAME}",
            "${PREV_TEST_STATUS}",
            "${REPORT_FILE}",
            "${SPACE}",
            "${SUITE_DOCUMENTATION}",
            "${SUITE_NAME}",
            "${SUITE_SOURCE}",
            "${TEMPDIR}",
            "${TEST_DOCUMENTATION}",
            "${TEST_NAME}",
            "${True}",
            "&{SUITE_METADATA}",
            "@{TEST_TAGS}"
        ],

    /*
        Path to internal database

        By default internal database is created in plugin installation
        directory, in database folder. Sometimes it could be useful to
        change the default database location.

        Example if the robot_framework_workspace is defined in the
        Sublime workspace file and user wants to change between
        different projects. Then it is useful to define
        robot_framework_database_path setting also be project specific.
        When the internal database is project specific, user does not
        recreate the database when the project is changed.

        The robot_framework_database_path must be a path to a folder.
        If the setting is not path to a folder, then the database
        is created in the plugin installation directory.

    */
    "robot_framework_database_path": false,

    /*
        Sublime Text log_commands

        This setting controls will the 'Robot Framework: Command Logging'
        command enable or disable the Sublime Text log_commands API call.
        If the robot_framework_log_commands setting evaluates as Python
        True, then log_commands API call is enabled. If setting
        evaluates as Python False, log_commands API call is disabled.

        If log_commands API call is enabled. all commands run from key
        bindings and the menu will be logged to the console.
    */
    "robot_framework_log_commands": true
}
`

My log is:
`
command: scan_index
Scaning done with rc: 0
Indexing done with rc: 0
command: scan
Scaning done with rc: 0
`

My scan_index.log

`
INFO:2016-05-23 15:41:51,220: Creating table for: BuiltIn
`

Attaching created jsons as well..

[index-BuiltIn-ca8f2e8d70641ce17b9b304086c19657.zip](https://github.com/andriyko/sublime-robot-framework-assistant/files/277476/index-BuiltIn-ca8f2e8d70641ce17b9b304086c19657.zip)
[BuiltIn-ca8f2e8d70641ce17b9b304086c19657.zip](https://github.com/andriyko/sublime-robot-framework-assistant/files/277477/BuiltIn-ca8f2e8d70641ce17b9b304086c19657.zip)

**Comment by aaltat** [comment]
Based on a quick look, the `robot_framework_workspace` is not correct. The setting must point to a folder where you store the `*. robot ` files, not in folder where Robot Framework is installed. In the previous messages you did seem to store `*. robot ` files in the desktop, so correct setting value would be `C:\\Users\\ralex\\Desktop`

**Comment by aaltat** [comment]
The zip file looks correct the to and could not spot any other obvious mistakes in the `Robot.sublime-settings` file. Please note that you do not need to define all the setting in the user specific `Robot.sublime-settings` file, you only need to define the settings which differ from the defaults. The only mandatory settings you need to define are the `robot_framework_workspace` and `path_to_python`. Those are user and OS specific settings and finding a setting that would match most of the needs is impossible.

**Comment by aaltat** [comment]
Did you get it working and can we close the issue or did you encounter more problems which should be resolved?

**Comment by aaltat** [comment]
Any updates?

**Comment by radinsky** [comment]
Sorry for the delay.
I confirm after changing the `robot_framework_workspace ` to the actual location of my *.robot files, it started working as expected.

**Comment by aaltat** [comment]
Good that it works. Because you did have that setting set incorrectly, do you think that the documentation should be enhanced. If yes, which way it should be enhanced?

**Comment by radinsky** [comment]
Check out my suggestion: 

`/*
        Robot Framework Workspace

        Defines a root folder where Test Suite located. 
        Before the Robot Framework Assistant can provide the keyword 
        and variable completion features, it needs to scan and index 
        the test suite and resource files. The argument defines the root folder 
        where scanning of robot data is performed.

        In windows the backslash is the folder separator and in json
        backslash is the escape character. Therefore, in windows write
        double backslash to write literal backslash.

        Linux example: \home\User\myRobotTests
        Windows example: "c:\\Users\\User\\Desktop\\myRobotTests"

    */`

**Comment by aaltat** [comment]
Looks good to me, do you want to make a pull request @

**Comment by radinsky** [comment]
yes, doing it now

**Comment by radinsky** [comment]
strange, can't push, getting denied on repository access right. I will try to push later at home.

**Comment by aaltat** [comment]
GitHub has good documentation from pull requests: https://help.github.com/articles/using-pull-requests/
