### ISSUE TITLE
Enable travis 

### ISSUE THREAD

**Issue by aaltat** [andriyko/sublime-robot-framework-assistant#43]
@andriyko would it be possible to you turn on the travis integration? It seems that only admin is able do that and collaborators can not do it. Could you login to https://travis-ci.org/ and follow these instructions: https://docs.travis-ci.com/user/getting-started

Once the build is enabled I can configure the `.travis.yml` and rest of the stuff

**Comment by andriyko** [comment]
@aaltat, Travis is enabled.

**Comment by aaltat** [comment]
I can see the repo in Travis and can do the rest. Thank you from the help.
