### ISSUE TITLE
VS Code support. 

### ISSUE THREAD

**Issue by ScenK** [andriyko/sublime-robot-framework-assistant#44]
Do you plan to support VS Code?

**Comment by aaltat** [comment]
I am not sure what you mean by VS Code, could you open the acronym?

**Comment by ScenK** [comment]
It`s the Visual Studio Code. https://github.com/Microsoft/vscode.

**Comment by aaltat** [comment]
Would you mind explaining your idea better? How would you write Robot Framework test data by using Visual Studio Code?

**Comment by ScenK** [comment]
Because of there are lack of robot framework highlight themes, as well as autocompleting keywords. I think it could just does what in sublime text does - run test files from current file, autocomplete keywords when i`m writing test cases files, some code snippets and, if it possible, rflint could be plugged in.

**Comment by aaltat** [comment]
This is what the current plugin is doing for Sublime Text. I don't have any plans to port this plugin from Sublime to any other editor.

There are some parts, specially in the upcoming 2.0 release, which could be made as independent projects and used in other people's projects. Example the parsing logic could be useful. If there is a need to separate, example the the parsing logic, I am willing to help but that isn't planned currently.

**Comment by ScenK** [comment]
It`s very kind of you. Thx.
