### ISSUE TITLE
Import Keywords and Variables into Symbol List

### ISSUE THREAD

**Issue by rfuentescruz** [andriyko/sublime-robot-framework-assistant#56]
One way to enable quick jumps to keyword and variable definitions is to simply import the parsed keywords into the symbol list. You might say that this is unnecessary given this plugin's scanners but this approach allows us to make symbol lookups without having to setup the interpreters and the scanners.

I got this sort of working with this `.tmPreferences` file. Happy to submit a PR if you think this is worth doing.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
   <key>name</key>
   <string>Symbol List</string>
   <key>scope</key>
   <string>text.robot keyword.control.robot</string>
   <key>settings</key>
   <dict>
      <key>showInSymbolList</key>
      <integer>1</integer>
      <key>showInIndexedSymbolList</key>
      <integer>1</integer>
   </dict>
</dict>
</plist>

```

**Comment by aaltat** [comment]
By a quick look it looks feature that is useful to have. Also update the README.md in the pull request.

There is a rewrite for the plugin going on, in here https://github.com/andriyko/sublime-robot-framework-assistant/tree/rewrite_to_version_2?files=1and I was planning to make a release 2.0.0 in this week. The enhancement looks relatively small so it could go to both versions with a small effort. Or are you targeting to a specific version?

**Comment by aaltat** [comment]
Thank you from the pull request. I am sick at the moment and I will take a look the pull request when I am feeling better.
