### ISSUE TITLE
Terminate current robot test case

### ISSUE THREAD

**Issue by ScenK** [andriyko/sublime-robot-framework-assistant#61]
Right now, the robot job could be triggered by "Run" in the current open file. Is there a way to terminate running jobs with something like 'control+c' in terminal?

**Comment by aaltat** [comment]
The only way to interrupt the test run, at least the only I have found, is to kill Sublime and it's child processes. 

The plugin uses the Sublime [build system](http://docs.sublimetext.info/en/latest/reference/build_systems/configuration.html) to run the test cases. And this actually is not the plugin problem but it is a general problem on the Sublime build system.

It is really annoying problem and there might be solution for it. I don't have time to investigate the issue more in the near future, but if you want to do it and make a pull request to fixit, I am happy to review the pull request.

If you plan to make a such thing, please note that plugin is being [rewritten](https://github.com/andriyko/sublime-robot-framework-assistant/tree/rewrite_to_version_2?files=1). The plan is to make release in this week.
