### ISSUE TITLE
Configuration confused on switch to new release

### ISSUE THREAD

**Issue by ScenK** [andriyko/sublime-robot-framework-assistant#68]
{
    "robot_framework_workspace": "/Users/Scen/Develop/Robot/",

    "path_to_python": "/usr/local/bin/python",

    "robot_framework_module_search_path":
        [
            "/usr/local/bin",
            "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip",
            "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7",
            "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin",
            "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac",
            "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages",
            "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk",
            "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old",
            "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload",
            "/usr/local/lib/python2.7/site-packages",
            "/Library/Python/2.7/site-packages",
        ],

    }

Above is my user-setting.json file. And when i run command "create database", error occurs in the sublime console, and the database could not be generated successful. Is there something i missed?

    File "/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/commands/scan_and_index.py", line 72, in add_builtin_vars
    f_table = open(table_path, 'r')
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/database/scanner/BuiltIn-ca8f2e8d70641ce17b9b304086c19657.json'

**Comment by aaltat** [comment]
I have also seen this error, now and then, but I haven't found a reason why it happens. The error is caused because it can't find the table, in this case the BuiltIn, when it creates a index for a test suite or a resource file. When I did investigate the error, each time the hash in the file name was not correctly calculated by the plugin. But I haven't got any further in my investigation because, for me, the error happens randomly only at the beginning when plugin is loaded and is therefore really hard to debug.

As a workaround, could you run the ```Robot Framework: Create Database Tables``` and then ```Robot Framework: Create Database Index From Active Tab```. If that works then you could try run the ```Robot Framework: Create Database```

**Comment by ScenK** [comment]
When i try to call Create Database Tables:

    Traceback (most recent call last):
    File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
    File "/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/commands/scan.py", line 28, in run
    file_
    File "/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework     Assistant/commands/scan.py", line 55, in run_scan
      startupinfo=startupinfo
    File "./subprocess.py", line 824, in __init__
    File "./subprocess.py", line 1386, in _execute_child
    TypeError: Can't convert 'list' object to str implicitly

**Comment by ScenK** [comment]
That occurs every time, and right now i could only run "Create Database Table From Active Tab" successfully. 

Further information: OSX 10.11. Python 2.7.11

**Comment by aaltat** [comment]
The ```Robot Framework: Create Database``` uses internally ```Robot Framework: Create Database Tables``` command and it if later fails the former should fail on the same problem. Therefore this kind a looks like a plugin loading problem.

Could you restart the Sublime, wait that plugins are loaded (time depends on the number of plugins) but 60s should be enough. And then rerun the ```Robot Framework: Create Database Tables``` and ```Robot Framework: Create Database Index From Active Tab``` commands.

**Comment by aaltat** [comment]
I did look the original error message more closely:
```
File "/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/commands/scan_and_index.py", line 72, in add_builtin_vars
f_table = open(table_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/database/scanner/BuiltIn-ca8f2e8d70641ce17b9b304086c19657.json'
``` 
It seems that this is a new issue and not the same issue which I have encountered. The hash in the `BuiltIn-ca8f2e8d70641ce17b9b304086c19657.json` is actually correct and therefore it seems that the `BuiltIn-ca8f2e8d70641ce17b9b304086c19657.json` is not in the where it should be.

When the plugin creates or updates the internal database, it writes events to a log file. The log file is overwritten when `Robot Framework: Create Database` and `Robot Framework: Create Database Tables` command are run. So could you re-run the `Robot Framework: Create Database` command and perhaps post the log file from `/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/database/scan_index.log`

Also this could be some OSX specific issue. To rule that one out, could you run the following commands from the Python (from same Python where Robot Framework is installed) prompt:
```
>>> from hashlib import md5
>>> md5('BuiltIn').hexdigest()
```
and send the output? 

Also please make sure that the `path_to_python` in our [user settings](http://docs.sublimetext.info/en/latest/customization/settings.html?highlight=user%20settings) has been configured to point the Python binary where Robot Framework is installed.

**Comment by ScenK** [comment]
I have tried your above steps but nothing help either.  What`s more, the scan_index.log is empty without any output.

Here are the outputs i run in terminal:
 
    In [1]: from hashlib import md5
    In [2]: md5('BuiltIn').hexdigest()
    Out[2]: 'ca8f2e8d70641ce17b9b304086c19657'

**Comment by aaltat** [comment]
Sorry did forget to ask but what is the error in the Sublime console then? Also from `/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/database/` folder, could you run command: `find .` to list all files and folders in that folder and subfolders.

**Comment by ScenK** [comment]
The sublime console error is the same as before.

    find .
    .
    ./scan_index.log
    ./scanner

**Comment by aaltat** [comment]
I will need to make you a modified `/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/commands/scan.py` so that I can see what are the Popen arguments.

**Comment by aaltat** [comment]
I have an idea, could you edit the user settings file, so that `robot_framework_module_search_path` contains only one path. Then run the `Framework: Create Database` command and could you send the console and log file output.

**Comment by aaltat** [comment]
After some debugging, I have found at least one reason why the error happens. If one have multiple entries in the `robot_framework_module_search_path` setting, the list is not properly handled and causes an error. It should be reflective easy to fix the plugin code to properly support multiple entries in the `robot_framework_module_search_path` setting,

**Comment by ScenK** [comment]
I have tried to limit `robot_framework_module_search_path` to only path, the issue still occurs. With empty scan_index.log

**Comment by aaltat** [comment]
Because the setting is actually a list, there might be difference how OSX handles a list the Python subprocess argument. But I also get it fail, in windows, if there are more than one item in the setting. I will fix it and make a new release.

**Comment by aaltat** [comment]
There was few other bugs when setting the `robot_framework_module_search_path` and https://github.com/andriyko/sublime-robot-framework-assistant/commit/db9afcb1925270309427d0667c5bb0d8da44ed5d should have fixed them all. I will create a new release and if you did install the package from package central you should get the update automatically. 

If encounter the same problem again, please send a update we will reopen the issue.

**Comment by aaltat** [comment]
The 3.0.2 now is released and available from the package control.
