### ISSUE TITLE
can't use the key “Ctrl+/” to toggle comment the .txt extenssion

### ISSUE THREAD

**Issue by darkmanno6** [andriyko/sublime-robot-framework-assistant#75]

**Comment by aaltat** [comment]
This is not been implement. Would you like to make a pull request to implement it?

**Comment by aaltat** [comment]
After reading the sublime [documentation](http://docs.sublimetext.info/en/latest/reference/comments.html) it seems that this is not difficult.

**Comment by aaltat** [comment]
This is available from the https://github.com/andriyko/sublime-robot-framework-assistant/pull/78 if you want to try it out. It will be part of the 3.1.0 release.

**Comment by aaltat** [comment]
Merged
