### ISSUE TITLE
Go to keyword resource not work

### ISSUE THREAD

**Issue by ScenK** [andriyko/sublime-robot-framework-assistant#80]
Release 3.0.2: Database could successful created and without error. But "Go to keyword" not work as expected.

**Comment by aaltat** [comment]
There are two ways to reach the keyword source. The `Robot Framework: Jump To Keyword` command and Sublime [Go To Symbol](http://docs.sublimetext.info/en/latest/file_management/file_management.html#fm-goto-symbol). The former uses the plugin internal database and the later is default Sublime feature. Could you tell which one you are using?

Also if you are using the former could you see if the log file contains any errors you should fix or would relevant to know. Also the console may contains errors. And last, is there a status message displayed in the status bar?

**Comment by aaltat** [comment]
Could your issue be same as: https://github.com/andriyko/sublime-robot-framework-assistant/issues/85?

**Comment by ScenK** [comment]
Yes. I think so.

**Comment by aaltat** [comment]
The (3.1.0](https://github.com/andriyko/sublime-robot-framework-assistant/releases/tag/st3-3.1.0) is out. Could you try that does it fix you problem?

**Comment by ScenK** [comment]
![screen shot 2016-04-26 at 7 09 08 am](https://cloud.githubusercontent.com/assets/2987542/14801693/e243ce7c-0b7d-11e6-90be-27e339b4a46a.png)
![screen shot 2016-04-26 at 7 09 21 am](https://cloud.githubusercontent.com/assets/2987542/14801695/e5739424-0b7d-11e6-801e-8a9fa799109c.png)

Two screenshot added. Only few keyword could jump successful.

**Comment by aaltat** [comment]
You are using a right click to access a context menu? The context menu is the default Sublime Text one and currently it doesn't contain the features that did exist in the 1.X.X. series. 

The context menu uses the Sublime Text Go To Symbol feature. This feature is only able to jump keywords which are defined in the same file. It's not able to jump keywords which are defined in other Robot data or in libraries. To use plugin jump to keyword feature, there are two ways to access that feature.

First, move the cursor on the keyword and press `Ctrl+Enter`. Or with the mouse, press `Alt` and left click on the desired keyword. Could you try one of those ways to jump to the keyword?

As a side note, if your preferred workflow is using the context menu, there is issue about it: https://github.com/andriyko/sublime-robot-framework-assistant/issues/45. Could you comment what type of items you would like to see in the context menu and in which order.

**Comment by ScenK** [comment]
Oh. Okey. My workflow is just alt+left click. Just forget the previous comment.

**Comment by aaltat** [comment]
Does the jump to keyword work when using the plugin commands? If it works can we close the issue then?

**Comment by ScenK** [comment]
No. Not work. Without error outputs in console.

**Comment by aaltat** [comment]
When you execute a jump to keyword, there should be a status message in bottom bar of the Sublime Text. Could you tell what the status message is saying?

**Comment by ScenK** [comment]
It shows only line:xxx, column:xxx. And some time it shows "Updating index is done for file: /Users/Scen/Develop/robot/tests/smoke/test.robot "

**Comment by aaltat** [comment]
That message is displayed after you have run one of the commands which update the internal database. There should be a different message when you move the cursor to the keyword and press `Alt+Enter`.  The message should start with word `File` or `Keyword`. If the message is not displayed, could you look at the console is there an error?

**Comment by ScenK** [comment]
Well it works with alt+enter right now, but still not work with alt+left click. Is there somewhere i can configure that?

**Comment by aaltat** [comment]
There is separate configuration for Windows, Linux and OSX for key and and mouse maps. The OSX [Default (OSX).sublime-mousemap](https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/Default%20(OSX).sublime-mousemap) defines the commands which works by using the mouse and key combination. It is identical to the Windows and Linux ones, but because I don't own a Mac I am not able to test it. 

Perhaps the file has a error or the configuration should be different for Mac. I can try to look some answer but can't be sure because I don't have access to a Mac.

**Comment by aaltat** [comment]
I did do some reading and found a way to debug your problem. Open the `/Users/Scen/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/commands/scan.py` file and add `sublime.log_commands(True)` line to the `run`function. Example it should look like this:
```
    def run(self, edit):
        """Command to scan RF files and create database tables

        Purpose of the command is iterate over the files found from
        the robot_framework_workspace and create database tables.
        Also all imports, from found files, will be iterated and
        table is created also from imports.
        """
        sublime.log_commands(True)
        log_file = get_setting(SettingObject.log_file)
```
Take apply changes to the plugin, restart Sublime. 

Run `Robot Framework: Create Database Tables` command. Open a robot data file from the your workspace, index the file with command: `Robot Framework: Create Database Index From Active Tab`. Open console, from `View -> Show Console`

Then perform the `Alt+Left Click` on the keyword and could send back what to console displays. In my windows machine, it shows this: 
```
Updating index is done for file: D:\workspace\sublime-robot-framework-assistant\test\resource\test_data\suite_tree\test_b.robot 
command: drag_select {"event": {"button": 1, "x": 502.5, "y": 177.5}}
command: jump_to_keyword {"event": {"button": 1, "x": 502.5, "y": 177.5}}
Updating index is done for file: d:\workspace\sublime-robot-framework-assistant\test\resource\test_data\suite_tree\resource_b.robot 
```

Once done, remove the `sublime.log_commands(True)` line from the `scan.py` file and restart Sublime.

**Comment by andriyko** [comment]
>sublime.log_commands(True)
>log_file = get_setting(SettingObject.log_file)
That looks like a nice improvement to have this configurable via settings and allow users to turn on debug mode if needed. It can be put in base class that is used to run commands.

**Comment by andriyko** [comment]
Or maybe Sublime itself has some config var that allows to log all commands.

**Comment by aaltat** [comment]
@andriyko Good idea and definitely worth of investigating how to do it the best way.

**Comment by aaltat** [comment]
Raised an issue: #103 so that idea is not forgotten.

**Comment by ScenK** [comment]
Now i found what cause the issue: there is an old mouse-map file in the root of the packages folder. And in that file defined old RF-Assistant mouse-map. Something like:

    {
      "button": "button1", "count": 1, "modifiers": ["alt"],
      "press_command": "drag_select",
      "command": "robot_framework_go_to_item_source"
    },

I remove that file, and every thing works fine. Thanks!

**Comment by aaltat** [comment]
Good that you did find the reason and the problem is fixed. Thank you from your patience.
