### ISSUE TITLE
Go to keyword source

### ISSUE THREAD

**Issue by huuhtaneno** [andriyko/sublime-robot-framework-assistant#85]
Hi,

When a keyword is prefixed with the a custom keyword library the "Go To Source" command does not work.

-Oliver

**Comment by aaltat** [comment]
It seems that this happens only when library is imported with file name, example: `path/to/LibraryName.py`

**Comment by aaltat** [comment]
Fixed in: https://github.com/aaltat/sublime-robot-framework-assistant/commit/f5ae55cd5c86a97d0e317b190e756c41d410ae49
