### ISSUE TITLE
project setting "robot_framework_workspace" does not have priority on package setting

### ISSUE THREAD

**Issue by antoine-gallix** [andriyko/sublime-robot-framework-assistant#93]
I try to define a "robot_framework_workspace" entry for each of my project, that obviously have different folders for robot tests. I add a "robot_framework_workspace" entry in the project .sublime-project file. However when trying to build the database, the log file says 
`EnvironmentError: Workspace does not exist: /path/to/folder/containing/robot/data` 
which means the project setting is not taken into account.
Is it even possible to define a robot workspace for each project?

**Comment by aaltat** [comment]
Currently this is [not possible](https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/setting/setting.py#L55) to define workspace for project. But you have valid point and it would be a good feature to have. Would you be interested to make a pull request to add support for projects?

**Comment by aaltat** [comment]
When thinking the idea little bit further, would you have many or single project open at the same time? If you would have many projects open at the same time, then the path for the internal database must be project specific too. So that user doesn't need to recreate the database each time they switched between projects. The database path is coded in the [setting.py](https://github.com/andriyko/sublime-robot-framework-assistant/blob/master/setting/setting.py) file but it is always read from the setting.py file by the commands. Having the project specific database adds some complexity but it is not overly complicated. It may be useful if you want to quickly check something between different projects and want to use plugin features which use the internal database.

But what you think, what would be your usage scenario?

**Comment by aaltat** [comment]
By reading the Sublime API doc, it looks like that reading project setting settings is easy task. Project settings can be read by the https://www.sublimetext.com/docs/3/api_reference.html#sublime.Window API, by using `project_data()` API call.

**Comment by aaltat** [comment]
I did implement your request. It is available from the #102 but it is not yet merged to the master. In my testing everything seemed to work OK but I would like to hear your feed back too. 

Could you download the pull request, from [add_support_for_project_settings](https://github.com/aaltat/sublime-robot-framework-assistant/tree/add_support_for_project_settings) branch, install it manually and give it a try?

**Comment by antoine-gallix** [comment]
Hi Tatu,
My abilities in programming are actually quite limited, so I didn't saw how
I could help understand the package so quick and do the fix. I'll try the
fix at work tomorow.
Antoine

*Antoine*

**Comment by aaltat** [comment]
It is not a problem, this is a good idea and I have similar need too.

The README.md is updated, in the branch, and gives a short description how to use project specific settings.

For me it was more than enough of documentation. But I have a feeling that for people who is not that experienced with Sublime, some more documentation is needed. Could take a look and give your opinion on the matter?

**Comment by antoine-gallix** [comment]
Ok so I tried the new version.
I set the workspace variable in my project settings as indicated. Doesn't work. It still looks for the default dummy path in the default settings.

from database/scan_index.log
```
Traceback (most recent call last):
  File "/home/antoine/.config/sublime-text-3/Packages/Robot Framework Assistant/dataparser/run_scanner.py", line 77, in <module>
    args.path_to_lib_in_xml)
  File "/home/antoine/.config/sublime-text-3/Packages/Robot Framework Assistant/dataparser/run_scanner.py", line 20, in scan_all
    db_path=db_path
  File "/home/antoine/.config/sublime-text-3/Packages/Robot Framework Assistant/dataparser/queue/scanner.py", line 42, in scan
    'Workspace does not exist: {0}'.format(str(workspace)))
EnvironmentError: Workspace does not exist: /path/to/folder/containing/robot/data

```

**Comment by aaltat** [comment]
Ok cool that it works. Any input on the documentation?

**Comment by aaltat** [comment]
I did found some testing and code reading I did found few bugs in the implementation. Also made the code more readable.

**Comment by aaltat** [comment]
I think this is now done. More testing did not reveal any issues. If you encounter problems, please raise an new issue.

**Comment by antoine-gallix** [comment]
The documentation is quite good, if I see some possible clarification I'll submit something!

**Comment by aaltat** [comment]
Ok, thank you from the input.
